version: '3.9'
services:
  edbox:
    container_name: sandboxjs
    image: 'registry.richardx.win/sandboxjs:latest'
    restart: unless-stopped
    ports:
      - '3005'
    labels:
      - traefik.enable=true
      - traefik.http.routers.sandboxjs.rule=Host(`sandboxjs.richardx.win`)
    environment:
      - PASSWORD=$PASSWORD

networks:
  default:
    name: proxy
    external: true
